rm(list = ls())
TeamDonar <- read.csv("/home/ubuntu/dataset/Team-Donor-Participant-Merge.csv", header = TRUE, sep = "," )
attach(TeamDonar)
TeamDonar$CaptainAcceptEmail <- as.logical(CaptainAcceptEmail)
TeamDonar$PriorYearParticipation <- as.logical(PriorYearParticipation)
TeamDonar$GenderMale <- as.numeric(GenderMale)
TeamDonar$GenderFemale <- as.numeric(GenderFemale)
TeamDonar$GenderNotSpecified <- as.numeric(GenderNotSpecified)
TeamDonar$RegOnline <- as.numeric(RegOnline)
TeamDonar$RegOffline <- as.numeric(RegOffline)
TeamDonar$PriorParticipant <- as.numeric(PriorParticipant)
TeamDonar$NotPriorParticipant <- as.numeric(NotPriorParticipant)
TeamDonar$ConnectionMS <- as.numeric(ConnectionMS)
TeamDonar$NoConnectionMS <- as.numeric(NoConnectionMS)
TeamDonar$RegActive <- as.numeric(RegActive)
TeamDonar$RegInActive <- as.numeric(RegInActive)
TeamDonar$DonorGenderMale <- as.numeric(DonorGenderMale)
TeamDonar$DonorGenderFemale <- as.numeric(DonorGenderFemale)
TeamDonar$DonorGenderNotSpecified <- as.numeric(DonorGenderNotSpecified)
TeamDonar$RegisteredDonors <- as.numeric(RegisteredDonors)
TeamDonar$NonRegisteredDonors <- as.numeric(NonRegisteredDonors)
TeamDonar$DonorConnectionMS <- as.numeric(DonorConnectionMS)
TeamDonar$DonorNoConnectionMS <- as.numeric(DonorNoConnectionMS)
TeamDonar$DonorPriorParticipant <- as.numeric(DonorPriorParticipant)
TeamDonar$DonorNotPriorParticipant <- as.numeric(DonorNotPriorParticipant)


str(TeamDonar)

summary(TeamDonar)

fit_donar <- lm(GiftAmount ~ CaptainAcceptEmail+PriorYearParticipation+GenderMale+GenderFemale+GenderNotSpecified+RegOnline+RegOffline+PriorParticipant+NotPriorParticipant+ConnectionMS+NoConnectionMS+RegActive+RegInActive+DonorGenderMale+DonorGenderFemale+DonorGenderNotSpecified+RegisteredDonors+NonRegisteredDonors+DonorConnectionMS+DonorNoConnectionMS+DonorPriorParticipant+DonorNotPriorParticipant)
#fit_donar <- lm(GiftAmount ~ CaptainAcceptEmail+GenderMale+GenderFemale+RegOnline+RegOffline+ConnectionMS+NoConnectionMS+DonorGenderMale+DonorGenderFemale+RegisteredDonors+NonRegisteredDonors+DonorConnectionMS+DonorNoConnectionMS+DonorPriorParticipant+DonorNotPriorParticipant)
#fit_donar <- lm(GiftAmount ~ CaptainAcceptEmail)
summary(fit_donar)
coef(fit_donar)
layout(matrix(1:4,2,2))
plot(fit_donar)

